apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo-pod
  template:
    metadata:
      labels:
        app: tickets-mongo-pod
    spec:
      containers:
        - name: tickets-mongo-container
          image: mongo

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  type: ClusterIP
  selector:
    app: tickets-mongo-pod
  ports:
    - name: tickets-port
      protocol: TCP
      port: 27017
      targetPort: 27017
