apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-pod
  template:
    metadata:
      labels:
        app: tickets-pod
    spec:
      containers:
        - name: tickets-container
          image: harsh253/tickets
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: mongodb://tickets-mongo-srv:27017/tickets

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  type: ClusterIP
  selector:
    app: tickets-pod
  ports:
    - name: tickets-port
      protocol: TCP
      port: 3000
      targetPort: 3000
